resource_group_name     = "KeyVaultRG"
resource_group_location = "West Europe"
keyvault_name           = "keyvault010203"
secret_name             = "DatabasePassword"
secret_value            = "P@ssw0rd1234!"