resource_group_name     = "WebAppSqlRG"
resource_group_location = "West Europe"
app_service_plan_name   = "example-appservice-plan"
app_service_name        = "terraform-app-1510611"
sql_server_name         = "terraform-sqlserver-1510611"
sql_admin_login         = "4dm1n157r470r"
sql_admin_password      = "4-v3ry-53cr37-p455w0rd"
sql_database_name       = "ProductsDB"
